Repository sardana-org/sardana, pull requests merged in 2018-09, with the labels that each got.

#923 Adding diffractometer types
  src/sardana/pool/poolcontrollers/HklPseudoMotorController.py
Labels: enhancement

#921 Adapting for 4c diffrac
  src/sardana/macroserver/macros/hkl.py
Labels: enhancement

#933 Move pre-scan and post-scan hooks out of scan_loop (issue-920; previously pr-922)
  src/sardana/macroserver/scan/gscan.py
Labels: bug

#876 Optional param
  doc/source/devel/howto_macros/macros_general.rst
  src/sardana/macroserver/macro.py
  src/sardana/macroserver/msparameter.py
  src/sardana/taurus/core/tango/sardana/macro.py
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
Labels: enhancement

#935 Do not fill missing records if timescan is stopped
  src/sardana/macroserver/scan/gscan.py
Labels: bug

#934 Document support of hooks when programming macros (Issue 820)
  doc/source/devel/howto_macros/macros_general.rst
  doc/source/users/macro_hooks.rst
Labels: doc

#936 Correct continuous scan hooks
  src/sardana/macroserver/macros/scan.py
Labels: bug

#764 Stop MG in case of starting failure
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: bug

#940 Provide MeasurementGrp as a parameter in ct macro
  src/sardana/macroserver/macros/standard.py
Labels: enhancement

#882 Update Experimental Configuration automatically
  src/sardana/spock/magic.py
  src/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py
  src/sardana/taurus/qt/qtcore/tango/sardana/pool.py
  src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Labels: enhancement

#942 Add protection on parameter info reading
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
Labels: bug
