Repository sardana-org/sardana, pull requests merged in 2018-11, with the labels that each got.

#781 Extend spock syntax
  doc/source/users/spock.rst
  src/sardana/macroserver/macro.py
  src/sardana/macroserver/macros/examples/parameters.py
  src/sardana/macroserver/macros/test/test_macro.py
  src/sardana/macroserver/macros/test/test_scanct.py
  src/sardana/macroserver/macros/test/test_standard.py
  src/sardana/macroserver/msmacromanager.py
  src/sardana/macroserver/msparameter.py
  src/sardana/macroserver/test/res/macros/testmacros.py
  src/sardana/spock/parser.py
  src/sardana/spock/spockms.py
  src/sardana/spock/test/test_parser.py
  src/sardana/tango/macroserver/test/base.py
  src/sardana/taurus/core/tango/sardana/macro.py
  src/sardana/taurus/core/tango/sardana/macroserver.py
  src/sardana/taurus/core/tango/sardana/test/test_macro.py
  src/sardana/util/parser.py
  src/sardana/util/test/test_parser.py
Labels: enhancement

#976 Fix bug on controller description reading
  src/sardana/pool/poolmetacontroller.py
Labels: bug

#943 MacroButton Stop macro instead direct Aborting
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
Labels: bug

#984 Document RConsolePort
  doc/source/users/configuration/macroserver.rst
Labels: doc

#986 Allow changes of pseudo counter data format (shape)
  doc/source/devel/howto_controllers/howto_controller.rst
  doc/source/devel/howto_controllers/howto_pseudocountercontroller.rst
  doc/source/glossary.rst
  src/sardana/tango/pool/PoolDevice.py
  src/sardana/tango/pool/PseudoCounter.py
Labels: enhancement

#990 Fix limits protection in ascanct when Taurus 4 is used
  src/sardana/macroserver/scan/gscan.py
Labels: bug

#988 Fix expconf for Qt 4.4 (signal style compatibility)
  src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Labels: bug
