Repository sardana-org/sardana, pull requests merged in 2018-08, with the labels that each got.

#885 Allows hooks in timescan
  src/sardana/macroserver/macros/scan.py
  src/sardana/macroserver/scan/gscan.py
Labels: bug

#759 Allow software synchronizer Initial domain configuration
  doc/source/devel/api/api_measurementgroup.rst
  src/sardana/pool/pooldefs.py
  src/sardana/pool/poolmeasurementgroup.py
  src/sardana/pool/poolsynchronization.py
  src/sardana/tango/pool/MeasurementGroup.py
  src/sardana/util/funcgenerator.py
Labels: enhancement

#887 Docu: Instrument
  doc/source/devel/overview/index.rst
  doc/source/devel/overview/overview_instrument.rst
Labels: doc

#893 Remove numpy and pylab from spock namespace
  src/sardana/spock/ipython_00_11/genutils.py
  src/sardana/spock/ipython_01_00/genutils.py
Labels: bug

#801 Add configuration attribute to DiscretePseudoMotorController
  src/sardana/macroserver/macros/discrete.py
  src/sardana/pool/poolcontrollers/DiscretePseudoMotorController.py
Labels: enhancement

#757 Calculation with real_vel instead ideal_vel
  src/sardana/macroserver/scan/gscan.py
Labels: enhancement

#810 Can not stop programmatic hooks
  src/sardana/macroserver/macro.py
Labels: bug

#758 Skip configuration loading for ctrls disabled.
  src/sardana/pool/poolmeasurementgroup.py
Labels: bug

#894 Store FQDN URI for Door and MacroServer in spock conf file
  src/sardana/spock/ipython_01_00/genutils.py
Labels: bug

#753 Fix Pre-Scan Snapshot
  src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Labels: bug

#768 Fix meshct intervals estimation
  src/sardana/macroserver/macros/scan.py
  src/sardana/macroserver/scan/gscan.py
Labels: bug

#892 Extend repeat macro to run it easily from spock
  src/sardana/macroserver/macros/standard.py
Labels: enhancement

#899 Fix pseudo counters in continuous acquisition.
  src/sardana/pool/poolpseudocounter.py
Labels: bug

#905 Increase timeout for door state events in BaseDoor
  src/sardana/taurus/core/tango/sardana/macroserver.py
Labels: bug, windows

#912 Revert "Can not stop programmatic hooks"
  src/sardana/macroserver/macro.py
Labels: bug
