Repository sardana-org/sardana, pull requests merged in 2019-02, with the labels that each got.

#1032 Improve macroexecutor error msg when loading settings
  src/sardana/taurus/core/tango/sardana/macroserver.py
Labels: bug

#1033 Make auto update action correctly restore its settings
  src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Labels: bug

#1031 Fix macroexecutor lineedit parameter editors
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/parameditors.py
Labels: bug

#997 Independent acquisition of timerable channels (#185)
  doc/source/devel/api/api_1D.rst
  doc/source/devel/api/api_2D.rst
  doc/source/devel/api/api_countertimer.rst
  doc/source/devel/howto_controllers/howto_countertimercontroller.rst
  src/sardana/pool/controller.py
  src/sardana/pool/poolbasechannel.py
  src/sardana/pool/poolcontroller.py
  src/sardana/pool/poolcontrollers/DummyCounterTimerController.py
  src/sardana/pool/poolcountertimer.py
  src/sardana/pool/poolonedexpchannel.py
  src/sardana/pool/pooltwodexpchannel.py
  src/sardana/pool/test/helper.py
  src/sardana/pool/test/test_ctacquisition.py
  src/sardana/pool/test/test_poolcountertimer.py
  src/sardana/tango/pool/CTExpChannel.py
  src/sardana/tango/pool/OneDExpChannel.py
  src/sardana/tango/pool/PoolDevice.py
  src/sardana/tango/pool/TwoDExpChannel.py
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: enhancement

#1041 Warn when hooks gets overridden
  src/sardana/macroserver/macro.py
Labels: enhancement

#1022 Add backwards compatibility for measurement group plot configuration (fixes #1017)
  src/sardana/pool/poolmeasurementgroup.py
Labels: bug

#1048 Fix independent acquisition when timer is set to __self
  src/sardana/pool/poolmeasurementgroup.py
Labels: bug

#1047 Acq acquisition macro example
  src/sardana/macroserver/macros/examples/acquisition.py
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: enhancement

#1049 Adapt ct and uct to accept timerable channels
  src/sardana/macroserver/macros/standard.py
  src/sardana/sardanadefs.py
Labels: enhancement

#1061 Prepare channel in independent acquisition
  src/sardana/pool/poolbasechannel.py
Labels: bug

#1060 Remove ms properties file in tests correctly on Windows
  src/sardana/tango/macroserver/test/base.py
Labels: bug, windows

#1062 Separate GH tests into two classes
  src/sardana/macroserver/macros/test/test_gh.py
Labels: bug

#1068 Remove ms_properties file after stopping MS
  src/sardana/tango/macroserver/test/base.py
Labels: bug
