Repository sardana-org/sardana, pull requests merged in 2020-05, with the labels that each got.

#1320 add a check for type keyword in spockms
  src/sardana/macroserver/macro.py
  src/sardana/spock/spockms.py
  src/sardana/tango/macroserver/Door.py
Labels: bug

#1326 Fix regscans points repeat
  src/sardana/macroserver/macros/examples/scans.py
Labels: bug

#1330 Build docs with Sphinx 3
  doc/source/conf.py
  doc/source/devel/api/api_test.rst
  doc/source/users/spock.rst
  src/sardana/macroserver/macros/test/base.py
  src/sardana/pool/controller.py
Labels: doc

#1308 Dump info on channels if MG acq fails in step scan, ct and uct
  src/sardana/macroserver/macros/standard.py
  src/sardana/macroserver/scan/gscan.py
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: enhancement

#1278 Macro combo box load after start
  doc/source/users/taurus/macroexecutor.rst
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
Labels: bug

#1288 Pmtv relies on encoder
  src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
Labels: bug

#1290 New style and text information for limit icons
  src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
Labels: enhancement

#1293 Reset pending operations on relative movement
  src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
Labels: bug

#1333 Register a TaurusValue factory for pool widgets
  setup.py
  src/sardana/taurus/qt/qtgui/extra_pool/formitemfactory.py
Labels: enhancement

#690 Add expconf macros module
  doc/source/devel/api/sardana/macroserver/macros.rst
  doc/source/devel/api/sardana/macroserver/macros/expconf.rst
  doc/source/users/standard_macro_catalog.rst
  src/sardana/macroserver/macros/env.py
  src/sardana/macroserver/macros/expconf.py
Labels: enhancement

#1284 Remove set use parent model
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/customeditors/senv.py
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/scanplotter.py
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/delegate.py
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py
Labels: enhancement

#1336 Fix dummy 1D: cast to int number of new frames
  src/sardana/pool/poolcontrollers/DummyOneDController.py
Labels: bug

#1335 Add direct links to Sardana-Taurus model API
  doc/source/devel/api/api_sardana.rst
  doc/source/devel/api/sardana/taurus/qt/qtcore/tango/sardana.rst
  doc/source/users/taurus/index.rst
Labels: doc

#1203 Improve channel TV widget
  src/sardana/taurus/qt/qtgui/extra_pool/__init__.py
  src/sardana/taurus/qt/qtgui/extra_pool/formitemfactory.py
  src/sardana/taurus/qt/qtgui/extra_pool/poolchannel.py
Labels: enhancement
