Repository sardana-org/sardana, pull requests merged in 2020-08, with the labels that each got.

#1341 Add docs on how to access Tango in macros and controllers
  doc/source/conf.py
  doc/source/devel/api/sardana/pool/poolutil.rst
  doc/source/devel/howto_controllers/howto_controller.rst
  doc/source/devel/howto_macros/macros_general.rst
  doc/source/users/faq.rst
  src/sardana/pool/poolutil.py
Labels: doc

#888 genv macro
  doc/source/users/standard_macro_catalog.rst
  src/sardana/macroserver/macros/env.py
Labels: enhancement

#824 plotselect macro
  doc/source/users/standard_macro_catalog.rst
  src/sardana/macroserver/macros/standard.py
Labels: enhancement

#890 pic cen where
  doc/source/users/environment_variable_catalog.rst
  doc/source/users/scan.rst
  doc/source/users/standard_macro_catalog.rst
  src/sardana/macroserver/macros/standard.py
Labels: enhancement

#1389 Document Sardana v2 -> v3 migration
  doc/source/devel/guide_migration/0to1.rst
  doc/source/devel/guide_migration/2to3.rst
  doc/source/devel/guide_migration/index.rst
  doc/source/devel/index.rst
  doc/source/users/taurus/macrobutton.rst
Labels: doc

#1397 Fix premature end of acquisition on Windows
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: bug, windows

#1398 Use proper python3 executable regardeless of installation
  src/sardana/spock/magic.py
  src/sardana/util/whichpython.py
Labels: bug

#1403 Make CounterTimerController.StartOne() re-implementation optional
  src/sardana/pool/controller.py
Labels: bug
