Repository sardana-org/sardana, pull requests merged in 2020-01, with the labels that each got.

#1266 Fix meas grp configuration URIs back compat
  src/sardana/pool/poolmeasurementgroup.py
Labels: bug

#1262 Improve gscan to detect if a file or dir path is set but empty in the…
  src/sardana/macroserver/scan/gscan.py
Labels: enhancement

#1260 Fix a showscan bug that loaded regular "showscan" and "showscan onlin…
  src/sardana/spock/magic.py
  src/sardana/spock/spockms.py
Labels: bug

#1242 merge of doorDebug and doorOutput
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/dooroutput.py
  src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py
Labels: enhancement

#951 Allow measurement groups renaming
  src/sardana/pool/pool.py
  src/sardana/pool/poolmeasurementgroup.py
Labels: bug

#1191 Better macro exception message
  src/sardana/macroserver/msmacromanager.py
Labels: enhancement

#1238 Fix #1237: Macro functions with result don't return any result
  src/sardana/macroserver/macro.py
Labels: bug

#1271 Fix meas grp configuration URIs back compat (measurement group's timer/monitor)
  src/sardana/pool/poolmeasurementgroup.py
Labels: bug

#1275 Add basic information to "how to write custom recorder" docs
  doc/source/devel/howto_recorders.rst
  doc/source/glossary.rst
  doc/source/users/configuration/macroserver.rst
  src/sardana/sardanacustomsettings.py
Labels: doc

#1280 Make sure pyplot examples correctly refresh plot on the client
  doc/source/devel/howto_macros/macros_general.rst
  src/sardana/macroserver/macros/examples/plotting.py
  src/sardana/macroserver/macros/examples/scans.py
Labels: doc, enhancement
