Repository sardana-org/sardana, pull requests merged in 2020-12, with the labels that each got.

#1442 Fix continuous readout of value references in hardware synchronized acquisition
  src/sardana/pool/poolacquisition.py
  src/sardana/pool/test/test_acquisition.py
Labels: bug

#1455 Disable flake8 job in travis CI
  .travis.yml
Labels: test

#1446 Leave Tango device class attributes definition untouched
  src/sardana/tango/pool/PoolDevice.py
Labels: bug

#1428 Fix delay description in position domain
  src/sardana/macroserver/scan/gscan.py
Labels: enhancement

#1424 Fix double unit shown in motor widget
  src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
Labels: enhancement

#1386 Add scan widgets
  doc/source/_static/showscan-online-infopanels.png
  doc/source/users/taurus/showscan.rst
  src/sardana/taurus/qt/qtgui/extra_sardana/showscanonline.py
  src/sardana/taurus/qt/qtgui/extra_sardana/ui/ScanInfoForm.ui
  src/sardana/taurus/qt/qtgui/extra_sardana/ui/ScanPointForm.ui
  src/sardana/taurus/qt/qtgui/extra_sardana/ui/ScanWindow.ui
  src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py
Labels: enhancement

#1355 Add custom user to scan
  doc/source/users/environment_variable_catalog.rst
  src/sardana/macroserver/scan/gscan.py
Labels: enhancement

#1427 Allow to programmatically disable *deterministic scan* optimization
  doc/source/devel/api/sardana/macroserver/scan.rst
  src/sardana/macroserver/scan/gscan.py
Labels: bug

#1216 Use uuid for MacroNode.id() in macroexecutor and sequencer
  src/sardana/taurus/core/tango/sardana/macro.py
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
  src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py
Labels: bug

#1456 Document Tango connection recycling and disposal.
  doc/source/devel/howto_macros/macros_general.rst
Labels: doc

#1422 Fix macro function default settings
  src/sardana/macroserver/macro.py
Labels: bug

#1460 Fix createMacro and prepareMacro docstring
  src/sardana/macroserver/macro.py
Labels: doc

#1443 Include TriggetGate elements in the per-measurement preparation
  doc/source/devel/api/api_controller.rst
  doc/source/devel/api/sardana/pool/controller.rst
  doc/source/devel/howto_controllers/howto_triggergatecontroller.rst
  doc/source/devel/howto_macros/scan_framework.rst
  src/sardana/pool/controller.py
  src/sardana/pool/poolacquisition.py
  src/sardana/pool/poolcontrollers/DummyTriggerGateController.py
Labels: enhancement

#1461 Document how to properly deal with exceptions in macros
  doc/source/devel/api/api_macro.rst
  doc/source/devel/howto_macros/macros_general.rst
  src/sardana/macroserver/macro.py
Labels: doc
