Repository sardana-org/sardana, pull requests merged in 2021-07, with the labels that each got.

#1627 Allow to run Sardana scripts as Python modules
  src/sardana/spock/__main__.py
  src/sardana/tango/__main__.py
  src/sardana/tango/macroserver/__main__.py
  src/sardana/tango/pool/__main__.py
  src/sardana/test/__main__.py
Labels: enhancement

#1622 fix: remove rfoo (rconsole) usage in sardana and in docs
  doc/source/users/configuration/macroserver.rst
  src/sardana/tango/core/util.py
  src/sardana/tango/macroserver/MacroServer.py
Labels: bug

#1626 Correcting example for fscan
  src/sardana/macroserver/macros/scan.py
Labels: doc

#1624 fix: provide back compat for external ctrls meas conf
  src/sardana/pool/poolmeasurementgroup.py
  src/sardana/tango/pool/MeasurementGroup.py
Labels: bug

#1640 fix: correctly extract taurus version
  src/sardana/spock/ipython_01_00/genutils.py
  src/sardana/tango/pool/test/base_sartest.py
Labels: bug

#1637 Fix #87 (error with duplicated pre-scan snapshots)
  src/sardana/macroserver/recorders/h5storage.py
  src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Labels: bug

#1625 fix: spock prompt informs when the Door is offline
  src/sardana/spock/ipython_01_00/genutils.py
Labels: bug

#1579 Stop motion only once in scans
  src/sardana/macroserver/msmacromanager.py
  src/sardana/taurus/core/tango/sardana/motion.py
Labels: bug

#1615 Udef checks dependencies
  src/sardana/macroserver/macros/test/test_scanct.py
  src/sardana/pool/pool.py
  src/sardana/pool/poolacquisition.py
  src/sardana/pool/poolbasechannel.py
  src/sardana/pool/poolbaseelement.py
  src/sardana/pool/poolcontroller.py
  src/sardana/pool/poolelement.py
  src/sardana/pool/poolmeasurementgroup.py
  src/sardana/sardanaevent.py
  src/sardana/tango/pool/Controller.py
  src/sardana/tango/pool/MeasurementGroup.py
  src/sardana/tango/pool/MotorGroup.py
  src/sardana/tango/pool/PseudoCounter.py
  src/sardana/tango/pool/PseudoMotor.py
  src/sardana/tango/pool/test/base_sartest.py
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: enhancement

#1620 fix: consider events from not standard 0D channel attributes
  src/sardana/tango/pool/ZeroDExpChannel.py
Labels: bug, daq

#1576 Allow to disable the overshoot correction on continuous scan
  doc/source/users/environment_variable_catalog.rst
  src/sardana/macroserver/scan/gscan.py
Labels: enhancement

#1669 Fix: Avoid cycle reference between h5 recorder and macro
  src/sardana/macroserver/recorders/h5storage.py
Labels: bug

#1672 fix: backward compatibility for meas grp conf value_ref_*
  src/sardana/pool/poolmeasurementgroup.py
Labels: bug
