Repository sardana-org/sardana, pull requests merged in 2021-01, with the labels that each got.

#1468 Fix signature of PrepareOne method on TriggerGateController
  src/sardana/pool/controller.py
Labels: bug

#1470 Complement and fix docs on setting ORBendPoint
  doc/source/users/configuration/server.rst
Labels: doc

#1469 Fix bug in string formatting
  src/sardana/pool/poolpseudomotor.py
Labels: bug

#1473 Make write of integration time more robust
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: bug

#1476 Add macro name and line to macro status 'start' event
  src/sardana/macroserver/macro.py
  src/sardana/macroserver/test/res/macros/testmacros.py
Labels: enhancement

#1479 Fix #1477: Launch showscan executable directly
  src/sardana/spock/magic.py
Labels: bug

#1434 Move testsuite from travis-ci to GH actions
  .github/workflows/tests.yaml
  .travis.yml
Labels: test

#1486 Fix PreScanSnapshot of strings
  src/sardana/macroserver/recorders/h5storage.py
Labels: bug

#1485 Fix NXscanH5_FileRecorder.addCustomData() with strings
  src/sardana/macroserver/recorders/h5storage.py
  src/sardana/macroserver/recorders/test/test_h5storage.py
Labels: bug

#1484 Fix example in docstring of QtSpockWidget
  src/sardana/taurus/qt/qtgui/extra_sardana/qtspock.py
Labels: doc
