Repository sardana-org/sardana, pull requests merged in 2021-06, with the labels that each got.

#1608 Hotfix 3.1.1: allow to stop/abort macro executing another hooked macro
  .bumpversion.cfg
  CHANGELOG.md
  doc/source/news.rst
  src/sardana/macroserver/msmacromanager.py
  src/sardana/release.py
  src/sardana/tango/macroserver/Door.py
Labels: bug

#1610 Update MeasurementGroup's Elements property when Configuration attr is written
  src/sardana/tango/pool/MeasurementGroup.py
Labels: bug

#1538 Execute post-scan also in case of an exception
  src/sardana/macroserver/scan/gscan.py
Labels: enhancement

#1607 Fix: completely clean client side after removing a measurement group
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: bug

#1616 [docs] Small fix on spock's `lsmac`/`lsdef` usage
  doc/source/users/spock.rst
Labels: doc

#1614 fix: hang of IPython when macro input gives timeout
  src/sardana/spock/inputhandler.py
  src/sardana/spock/ipython_01_00/genutils.py
Labels: bug
