Repository sardana-org/sardana, pull requests merged in 2021-05, with the labels that each got.

#1577 fix: do not reserve instruments in GScan
  src/sardana/macroserver/scan/gscan.py
Labels: bug

#1580 Improve installation instructions
  doc/source/users/getting_started/installing.rst
Labels: doc

#1583 bump taurus requirement to >= 4.7.1.1 on windows
  setup.py
Labels: windows

#1584 Add "What's new?" section to docs
  CHANGELOG.md
  doc/source/devel/howto_controllers/howto_1dcontroller.rst
  doc/source/docs.rst
  doc/source/news.rst
  doc/source/users/faq.rst
  doc/source/users/spock.rst
  doc/source/users/taurus/poolchanneltv.rst
  doc/source/users/taurus/poolmotortv.rst
  doc/source/users/taurus/showscan.rst
Labels: doc

#1592 Do not try to start operation when state is Moving
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: enhancement

#1593 Use AttributeEventWait.waitForEvent() instead of deprecated AttributeEventWait.waitEvent()
  setup.py
  src/sardana/taurus/core/tango/sardana/macroserver.py
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: bug

#1594 Allow to start PoolElement only when it is in On or Alarm states
  src/sardana/taurus/core/tango/sardana/pool.py
Labels: bug

#1595 Fix stop/abort element in ct macro when used with channels
  src/sardana/macroserver/macros/standard.py
Labels: bug

#1540 Fix1537 move regscan to scans
  doc/source/users/standard_macro_catalog.rst
  src/sardana/macroserver/macros/examples/scans.py
  src/sardana/macroserver/macros/scan.py
Labels: enhancement

#1599 Add lsp macro
  doc/source/users/standard_macro_catalog.rst
  src/sardana/macroserver/macros/lists.py
Labels: enhancement
